# Generated by Django 4.2.5 on 2023-09-08 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_firstname', models.CharField(max_length=200)),
                ('vendor_lastname', models.CharField(max_length=200)),
                ('vendor_username', models.CharField(max_length=20)),
                ('vendor_password', models.CharField(max_length=50)),
                ('vendor_address', models.CharField(max_length=50)),
                ('vendor_contact1', models.CharField(max_length=10, unique=True)),
                ('vendor_contact2', models.CharField(blank=True, max_length=10, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(max_length=200)),
                ('consignee_address', models.CharField(max_length=200)),
                ('consignee_phone', models.CharField(max_length=10)),
                ('consignment_est_wt', models.FloatField()),
                ('consignment_value', models.FloatField()),
                ('consignment_payment_type', models.CharField(choices=[('COD', 'COD'), ('Pre', 'Pre-Payment')], max_length=20)),
                ('consignment_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
