# Generated by Django 4.2.5 on 2023-09-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(max_length=200)),
                ('consignee_address', models.CharField(max_length=200)),
                ('consignee_phone', models.CharField(max_length=10)),
                ('consignment_est_wt', models.FloatField()),
                ('consignment_value', models.FloatField()),
                ('consignment_payment_type', models.CharField(choices=[('COD', 'COD'), ('Pre', 'Pre-Payment')], max_length=20)),
                ('consignment_id', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
