# Generated by Django 4.2.5 on 2023-09-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='consignment_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
