# Generated by Django 4.2.5 on 2023-09-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0003_vendor_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_account',
            name='vendor_contact1',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor_account',
            name='vendor_contact2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
